### ISSUE TITLE
ERROR: Cookies are blocked due to unexpected output.

### ISSUE THREAD

**Issue by imadlatch** [CleanTalk/anti-ddos-lite#1]
I get this error when I hit login button to WordPress admin
how do I fix it ?

thanks

**Comment by shagimuratov** [comment]
Hello @imadlatch,

Please try this,
1. Rename WP_ROOT/wp-content/plugins/cleantalk-spam-protect.
2. Try to login again. 

Does it help?

If not, please Google the error message,
https://www.google.com/search?q=Cookies+are+blocked+due+to+unexpected+output&oq=Cookies+are+blocked+due+to+unexpected+output&aqs=chrome..69i57j69i61l3.239j0j7&sourceid=chrome&ie=UTF-8

Thank you.
