### ISSUE TITLE
The Facebook Crawler, Google bot are can't visit my site.

### ISSUE THREAD

**Issue by amarsoft** [CleanTalk/anti-ddos-lite#11]
Hello
The Facebook Crawler, Google bot are can't visit my site.
my  not_rated_ua.php
$not_rated_ua = array(
    'Googlebot', 'Bingbot', 'Baiduspider','YandexBot',
    'facebot','facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)',
    'ia_archiver'
);

**Comment by shagimuratov** [comment]
Thanks, fixed!
https://github.com/CleanTalk/anti-ddos-lite/blob/master/not_rated_ua.php
