### ISSUE TITLE
cloudflare

### ISSUE THREAD

**Issue by N07R073X** [CleanTalk/anti-ddos-lite#12]
I use Cloudflare when I refresh I get the anti-DDoS page every time and it loops 3-4 times.

**Comment by shagimuratov** [comment]
Thanks for the report. Please let us 1-2 weeks to figure out the issue.

**Comment by ArtemAnoshin** [comment]
Hi! 
Fixed the problem with the lock screen looping. You can tell the archive by the link.

I will be glad if you confirm the solution of the problem!

https://github.com/CleanTalk/anti-ddos-lite/releases/download/DEV/anti-ddos-lite.zip

**Comment by N07R073X** [comment]
hi thanks @ArtemAnoshin, I'll try it soon.
