### ISSUE TITLE
Vivo Browser and Internet Archive stuck in endless reloading loop

### ISSUE THREAD

**Issue by thedoggybrad** [CleanTalk/anti-ddos-lite#19]
I have tested https://gosocial.x10.bz/ with this tool installed (modified a bit the GUI) and it works on every browser I tested and it passes the test.

What is weird is that Vivo browser (FuntouchOS Android), does not fail or pass it. I mean just stucked reloading and reloading on the same check page.

User agent of the problematic browser.
Mozilla/5.0 (Linux; Android 12; vivo 1919; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/87.0.4280.141 Mobile Safari/537.36 VivoBrowser/10.1.2.0

It is not Javascript related because it is enabled and I actually tried testing it with JS disabled on Brave browser and it shows a failed test, which is expected. But with Vivo Browser, no pass or fail. Just stucked on the same HTML Page. I do not know what's happening.

**Comment by thedoggybrad** [comment]
Update: After disguising Firefox as Mozilla/5.0 (Linux; Android 12; vivo 1919; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/87.0.4280.141 Mobile Safari/537.36 VivoBrowser/10.1.2.0

It turns out that the issue was not the user agent but the browser itself (Vivo Browser). I am sad to say that as of the moment, all of my web browsers that I tested passed the test except for Vivo Browser. Everything is fine on other web browsers, like it says if it pass or failed the test but not in the case of Vivo Browser.

@CleanTalk should I contact Vivo instead or you can still help me?

**Comment by alexandergull** [comment]
Hello, @thedoggybrad. 

Please, give us a few days to inspect your case.

**Comment by thedoggybrad** [comment]
@alexandergull Any updates on what happened?

By the way, another observation was the browser keeps reloading and reloading on the same anti-ddos page and clicking the link does the same. It seems like for me that something is not supported by the web browser.

**Comment by svfcode** [comment]
We are exploring the possibility to optimize the plugin for this browser.

**Comment by thedoggybrad** [comment]
@svfcode and @alexandergull 
Also, it seems like the Internet Archive's WayBackMachine is also stuck in this reloading loop.

Have a look right here: https://web.archive.org/web/20230528035019/https://gosocial.x10.bz/

**Comment by ArtemAnoshin** [comment]
Hello,

Could you please send us to our email support@cleantalk.org screenshots of Vivo browser settings, especially cookie settings?

**Comment by thedoggybrad** [comment]
@ArtemAnoshin I am sorry, there is no such cookie settings in there. I mean this is a basic web browser.

**Comment by thedoggybrad** [comment]
@ArtemAnoshin I think the issue is that this browser cannot support the protocols or whatever method this plugin uses and just keeps going back to same page.

I even clicked the link and the same thing happens.

**Comment by ArtemAnoshin** [comment]
@thedoggybrad 
The fact is that Vivo browser is not installed on our devices, apparently this is a very narrow segment of devices.
We will discuss and report on the problem with WebArchive separately.

**Comment by ArtemAnoshin** [comment]
Thank you for your message and observations. Unfortunately, at the moment we do not plan to deal with problems with the Vivo browser and the Web Archive service, due to the small audience of these products.
