### ISSUE TITLE
Delete.

### ISSUE THREAD

**Issue by cyberghostbg** [CleanTalk/anti-ddos-lite#2]
Delete.

**Comment by CleanTalk** [comment]
Hi @cyberghostbg,

Just let me know if you still need any assistance.

Thanks.

**Comment by IllegalMafia** [comment]
> Hi @cyberghostbg,
> 
> Just let me know if you still need any assistance.
> 
> Thanks.

hello 5 second pass refreshes the page to the normal page throws how can I solve

> Hi @cyberghostbg,
> 
> Just let me know if you still need any assistance.
> 
> Thanks.

hello 5 second pass refreshes the page to the normal page throws how can I solve

**Comment by IllegalMafia** [comment]
> Hi @cyberghostbg,
> 
> Just let me know if you still need any assistance.
> 
> Thanks.

hello 5 second pass refreshes the page to the normal page throws how can I solve
