### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by IllegalMafia** [CleanTalk/anti-ddos-lite#3]
hello 5 second pass refreshes the page to the normal page throws how can I solve

**Comment by CleanTalk** [comment]
Hello,

It's normal behavior for the app. It stops only for N seconds legitimate visitors (because of theirs browsers support JavaScript) and ban forever bots, because they can run JavaScript.

Let me know if you have questions.

**Comment by IllegalMafia** [comment]
> Merhaba,
> 
> Bu uygulama için normal bir davranış. Yalnızca N saniye boyunca meşru kılan ziyaretçiler (tarayıcıları JavaScript'i desteklediği için) durur ve sonsuza dek botları yasaklar çünkü JavaScript'i çalıştırabilir.
> 
> Sorunuz olursa lütfen bana söyleyin.

how can i make this application like cloudflare 5 seconds

my English is bad
