### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by IllegalMafia** [CleanTalk/anti-ddos-lite#4]
Why does it stay on the white screen when I add css
I'll be glad, if you help me

**Comment by CleanTalk** [comment]
Could you please provide some code example?

We need any details to help you.

**Comment by IllegalMafia** [comment]
code https://github.com/CleanTalk/anti-ddos-lite/blob/master/anti-ddos.html

**Comment by IllegalMafia** [comment]
sample code: https://pastebin.com/tQUN1W5H

**Comment by IllegalMafia** [comment]
https://pastebin.com/tQUN1W5H This happens when you make this code https://illegalmafia.com/testss/

**Comment by IllegalMafia** [comment]
https://illegalmafia.com/testss/anti-ddos.html

**Comment by IllegalMafia** [comment]
Why does this happen when you add css 
 https://illegalmafia.com/testss/

**Comment by IllegalMafia** [comment]
original version no problem https://illegalmafia.com/testss2/
css is such a problem when you add
https://illegalmafia.com/testss/

**Comment by CleanTalk** [comment]
Looks like you have JavaScript errors on the page. Please see attached screenshot and try to fix.

Does it help?
<img width="1440" alt="Screenshot 2019-10-24 at 15 14 29" src="https://user-images.githubusercontent.com/5357627/67476275-22f91f80-f671-11e9-8e86-05212b6d323f.png">

**Comment by IllegalMafia** [comment]
where is the error https://pastebin.com/tQUN1W5H

**Comment by IllegalMafia** [comment]
> Why does it stay on the white screen when I add css
> I'll be glad, if you help me
