### ISSUE TITLE
we can hack it.

### ISSUE THREAD

**Issue by guddumodok** [CleanTalk/anti-ddos-lite#8]
we used loop hole attack with jquery
$.POST("php",function(d,e){
clear all cookie///////// run again with for loop
})

**Comment by AfricansCantSwim** [comment]
you cant hack my site

**Comment by shagimuratov** [comment]
App works as a first line against bots attacks, it helps until an attacker fix his app.

If you want to completely mitigate a DDoS attack, you have to use additional solutions for sure. Anyway, you are welcome to pull your solutions :)
